"""
Minimal student-facing pipeline for the heart-expression imputation project.

This script runs the existing project commands in the intended order:
1. train HYFA/TopoHYFA
2. evaluate and save interpretability outputs
3. compare against the PCA + linear baseline
4. run the downstream SEX prediction task
5. generate interpretability figures

The defaults match the files generated by prep_handoff.py.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
import pandas as pd
import numpy as np


def run(cmd: list[str], env: dict[str, str]) -> None:
    print("\n$ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, env=env)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the simplified TopoHYFA student pipeline")
    parser.add_argument("--skip-train", action="store_true", help="Reuse existing data/model.pth")
    parser.add_argument("--lambda-reg", type=float, default=0.0)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--target-genes", default="Imputation/output/HYFA_export/target_genes_15.csv")
    parser.add_argument(
        "--genes", nargs="+", help="List of gene symbols to evaluate (overrides --target-genes)",
    )
    parser.add_argument("--topology-matrix", default="Imputation/output/HYFA_export/adjacency_matrix.csv")
    parser.add_argument("--confounders", default="Imputation/output/HYFA_export/confounders.csv")
    parser.add_argument("--interpretability-dir", default="results/interpretability")
    parser.add_argument("--figures-dir", default="results/interpretability_figures")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    env = {**os.environ, "WANDB_MODE": "disabled", "MPLCONFIGDIR": "/tmp/matplotlib"}
    py = sys.executable

    # If user provided gene symbols directly, create a small CSV matching
    # the project's expected `target_genes` format (one row, gene symbols as columns).
    if getattr(args, "genes", None):
        # Validate genes against adjacency matrix columns
        try:
            adj_cols = pd.read_csv(args.topology_matrix, index_col=0, nrows=0).columns.to_list()
        except Exception as e:
            raise FileNotFoundError(f"Could not read adjacency matrix {args.topology_matrix}: {e}")
        
        # Filter to only genes present in adjacency matrix
        valid_genes = [g for g in args.genes if g in adj_cols]
        missing_genes = [g for g in args.genes if g not in adj_cols]
        
        if not valid_genes:
            raise ValueError(
                f"None of the requested genes {args.genes} found in adjacency matrix. "
                f"Available genes: {adj_cols}"
            )
        
        if missing_genes:
            print(f"⚠️  Skipping genes not in adjacency matrix: {missing_genes}")
        
        print(f"✓ Using genes from adjacency matrix: {valid_genes}")
        
        cli_path = Path("Imputation/output/HYFA_export/target_genes_cli.csv")
        cli_path.parent.mkdir(parents=True, exist_ok=True)
        df = pd.DataFrame([np.zeros(len(valid_genes))], columns=valid_genes)
        df.to_csv(cli_path, index=True)
        args.target_genes = str(cli_path)
        print(f"Wrote {len(valid_genes)} valid genes to {args.target_genes}")

    for required in [args.target_genes, args.topology_matrix, args.confounders]:
        if not Path(required).exists():
            raise FileNotFoundError(required)

    if not args.skip_train:
        run(
            [
                py,
                "train_gtex.py",
                "--interpretability",
                "--num-workers",
                str(args.num_workers),
                "--target-genes",
                args.target_genes,
                "--topology-matrix",
                args.topology_matrix,
                "--confounders",
                args.confounders,
                "--lambda-reg",
                str(args.lambda_reg),
                "--source-tissue",
                "Whole_Blood",
                "--target-tissue",
                "Heart_L_Vent",
            ],
            env,
        )

    run(
        [
            py,
            "eval_15.py",
            "--interpretability",
            "--interpretability-output-dir",
            args.interpretability_dir,
        ],
        env,
    )
    run([py, "benchmark_teebot.py"], env)
    run([py, "run_disease_prediction.py", "--phenotype", "SEX"], env)
    run(
        [
            py,
            "visualize_interpretability.py",
            "--input-dir",
            args.interpretability_dir,
            "--top-k",
            "15",
            "--gene-names-csv",
            "results/hyfa_predictions_test.csv",
            "--output-dir",
            args.figures_dir,
        ],
        env,
    )


if __name__ == "__main__":
    main()
